---
title: "HW-3(Markov)"
author: "Emery Berry"
format: pdf
editor: visual
---

**Question 1, part d)**

```{r}
# parameters
a_star <- sqrt(3) - 1
c_star <- exp(-a_star) / (3 * a_star^2 * (1 - a_star))

# define densities
f <- function(x) (1/3) * x * (1 + x) * exp(-x)
g <- function(x, a) a^2 * x * exp(-a * x)

# choose a plotting range (adjust if you want)
xmax <- 20

# plot f(x)
curve(f(x), from = 0, to = xmax, n = 2000,
      xlab = "x", ylab = "density",
      main = "Target f(x) and envelope c(a*) g_{a*}(x)")

# add envelope curve
curve(c_star * g(x, a_star), from = 0, to = xmax, n = 2000,
      add = TRUE, lty = 2)

legend("topright",
       legend = c(expression(f(x)),
                  expression(c(a^"*") * g[a^"*"](x))),
       lty = c(1, 2), bty = "n")
```

**Question 2, part e)**

```{r}
P <- matrix(c(9/10, 1/10, 0,
              0,    7/8,  1/8,
              2/5,  0,    3/5),
            nrow = 3, byrow = TRUE)

P50 <- P
for (i in 2:50) P50 <- P50 %*% P
P50

# stationary distribution from part (d)
pi <- c(20/41, 16/41, 5/41)
pi
```

**Question 2, part f)**

```{r}
set.seed(1)

states <- c("G","S","D")
P <- matrix(c(9/10, 1/10, 0,
              0,    7/8,  1/8,
              2/5,  0,    3/5),
            nrow = 3, byrow = TRUE)

n <- 10000
x <- character(n)
x[1] <- "G"

for (t in 2:n) {
  i <- match(x[t-1], states)
  x[t] <- sample(states, size = 1, prob = P[i, ])
}

fracG <- mean(x == "G")
fracG
10/20.5 #Value from part d)
```

**Question 4, part c)**

```{r}
set.seed(1)

# Transition matrix P (states 1..6)
P <- matrix(c(
  1/2, 1/2, 0,   0,   0, 0,
  0,   1/2, 1/2, 0,   0, 0,
  1/3, 0,   1/3, 1/3, 0, 0,
  0,   0,   0,   1/2, 1/2, 0,
  0,   0,   0,   0,   0, 1,
  0,   0,   0,   0,   1, 0
), nrow = 6, byrow = TRUE)

states <- 1:6
N <- 10000
count4 <- 0

for (m in 1:N) {
  x <- 1  # start at X0 = 1
  for (t in 1:5) {
    x <- sample(states, size = 1, prob = P[x, ])
  }
  if (x == 4) count4 <- count4 + 1
}

frac <- count4 / N
frac                      # simulated estimate
19/108                    # Value from part (b)
```
